services:
  - type: web
    name: lb2-render-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: LB2 Render Demo
      - key: APP_ENV
        value: production
      - key: APP_VERSION
        value: 1.0.0
      - key: PORT
        value: 10000
      - key: USERS_SERVICE_URL
        value: https://lb2-users-service.onrender.com
      - key: TASKS_SERVICE_URL
        value: https://lb2-tasks-service.onrender.com
      - key: ANALYTICS_SERVICE_URL
        value: https://lb2-analytics-service.onrender.com

  - type: web
    name: lb2-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: LB2 Frontend
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8080

  - type: web
    name: lb2-users-service
    runtime: docker
    plan: free
    dockerfilePath: ./services/users_service/Dockerfile
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8001
      - key: DATABASE_URL
        value: postgresql+psycopg://lb2_postgres_user:x18ZfLCW212hZvOA71xmyHD4yMyF3jHm@dpg-d89im83bc2fs73f94j4g-a/lb2_postgres

  - type: web
    name: lb2-tasks-service
    runtime: docker
    plan: free
    dockerfilePath: ./services/tasks_service/Dockerfile
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8002
      - key: DATABASE_URL
        value: postgresql+psycopg://lb2_postgres_user:x18ZfLCW212hZvOA71xmyHD4yMyF3jHm@dpg-d89im83bc2fs73f94j4g-a/lb2_postgres

  - type: web
    name: lb2-analytics-service
    runtime: docker
    plan: free
    dockerfilePath: ./services/analytics_service/Dockerfile
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8003
      - key: DATABASE_URL
        value: postgresql+psycopg://lb2_postgres_user:x18ZfLCW212hZvOA71xmyHD4yMyF3jHm@dpg-d89im83bc2fs73f94j4g-a/lb2_postgres
